Iter5
korobkovandrey/runtime-metrics pull request #5
Opened 2024-12-02 19:22 UTC by korobkovandrey

2024-12-04 16:28 UTC, s-shpak requested changes
Сейчас код написан очень сложно и очень плохо читаемо. Упрости код по максимуму, выкинь из него все, что не требуется по ТЗ. Код, в целом, должен укладываться в 1000 строк с тестами без особых проблем. Упрощай, упрощай, упрощай.

1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-12-04 16:28 UTC, s-shpak commented on .golangci-1.62.yml
Зачем этот файл ?

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +		time.Sleep(time.Second)
Это значение ведь необходимо конфигурировать при запуске агента ?

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +				log.Println(fmt.Errorf(`dataWorker: %w`, err))
```suggestion
				log.Printf("dataWorker: %v", err)
```

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +			log.Println(err)
Можно ли продолжить выполнение цикла после возникновения этой ошибки ?

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +	UpdateCounterURL   string
YAGNI. Сервер принимает запросы по одному и тому же адресу

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +			log.Println(err)
В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где

2024-12-04 16:28 UTC, s-shpak commented on internal/agent/utils/utils.go
> +func convertReflectValueToString(value reflect.Value) (string, error) {
Не надо использовать рефлексию. Захардкодь значения

2024-12-04 16:28 UTC, s-shpak commented on internal/server/controller/index.go
> +		_, err := fmt.Fprintln(w, `<table><thead><tr><th>Type</th><th>Name</th><th>Value</th></tr><thead><tbody>`)
Для работы с `HTML` документами лучше использовать пакет html/template: https://pkg.go.dev/html/template

2024-12-04 16:28 UTC, s-shpak commented on internal/server/controller/update.go
> +		if t == `` {
```suggestion
		if t == "" {
```

2024-12-04 17:06 UTC, korobkovandrey commented on .golangci-1.62.yml
Я локально поставил свежий линтер 1.62.2 - ругался на execinquery как удаленный и gomnd требовал заменить на mnd, поэтому сделал отдельный конфиг, чтобы и изначальную версию в докере оставить.
А локально поставил, потому что в докере долго линтит - в районе 20-30сек, локальный за пару сек.
В принципе в докере мне не нужен - убрать его?

2024-12-04 18:00 UTC, korobkovandrey commented on internal/agent/agent.go
> +		time.Sleep(time.Second)
Рядом комментарий подчеркивает, что сознательно сделано. И функция названа dataWorker, а не pollMetrics или типа того.
Смысл такой - dataWorker отрабатывает раз в секунду, внутри проверяет не пора ли собрать метрики:
```go
		// получение данных раз PollInterval
		if a.collectExpire.Before(time.Now()) {
			a.collectExpire = time.Now().Add(a.config.PollInterval)
			err = a.gaugeSource.Collect()
```
т.е. собирает раз в PollInterval

и далее собирает какие метрики пора отправить:
```go
		// метрики, которые не отправлялись дольше ReportInterval
		dataForSend := a.gaugeSource.GetDataForSend(a.config.dataExpireTimeout, a.config.ReportInterval)
```

все это работает на принципе таймаутов у сущностей, а не на общем интервале отправки.
т.е. у сущности задается expire = 0, далее в цикле
если expire < текущего времени - делаем действие, устанавливаем expire = текущее время + интервал
все следующие проходы циклы до окончания интервала условие не выполняется - действия нет.

Т.е. dataWorker полностью отвечает за работу с in-memory хранилищем - собирает метрики и направляет их в отправку (другие воркеры хранилища не касаются). Тем самым наборы на отправку ввиду задержек распределяются во времени и на сервер идет не раз в 10 сек весь набор разом (в начале идет разом), а постепенно распределяются. Но каждая отдельно метрика - отправляется раз в reportInterval.

А через обратный канал воркер получает данные о времени успешной отправке - устанавливается в сущность - и следующая отправка этой метрики считается от этого времени. Если же сообщение об успехе не получено, то идет на повторную отправку спустя меньшее время. Обратный канал - история про контроль над повторными отправками в случае неуспеха.

А в целом - зарубился с каналами и идея была как должно это работать - думаю получилось реализовать, требованиям тз также полностью отвечает.

Переписываю на интервальный сбор и отправку + мьютексы для разделения доступа?

2024-12-04 18:12 UTC, korobkovandrey commented on internal/agent/utils/utils.go
> +func convertReflectValueToString(value reflect.Value) (string, error) {
Правильно понимаю, прописать в result каждую метрику отдельно?
```go
func GetRuntimeMetrics(fields ...string) (result map[string]string) {
	result = map[string]string{}
	memStats := &runtime.MemStats{}
	runtime.ReadMemStats(memStats)
	// add:
	result["Alloc"] = strconv.Itoa(int(memStats.Alloc))
	// ...
```

2024-12-04 18:26 UTC, korobkovandrey commented on internal/agent/agent.go
> +	sentChan      chan sentMessage
Смысл в принципе работы. При такой реализации отправка метрик идет на все скопом раз в reportInterval, а распределяется во времени (не сразу, зависит от задержки), также учитываются ошибки отправки.

Согласен, что для этой задачи сам себе усложнил условия, в целом ниже описал принципы, вопрос тот же - переписать на интервальный сбор/отправку и in-memory хранилище с мьютексами?

2024-12-06 16:00 UTC, s-shpak commented on internal/agent/utils/utils.go
> +func convertReflectValueToString(value reflect.Value) (string, error) {
Да, здесь будет лучше сделать именно так. Рефлексию можно использовать когда:
1. она применяется не для повторяющейся функции (например при set up или tear down сервиса)
2. нет другого выбора

2024-12-06 16:28 UTC, s-shpak requested changes

2024-12-06 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +	if err != nil {
В Go принято сначала делать проверку на ошибку. Если ошибка возникла, то, согласно конвенции, первое возвращенное значение не валдино, его нельзя использовать никак (закрывать тело ответа тоже не нужно)

2024-12-06 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +		err = fmt.Errorf("code %d", response.StatusCode)
```suggestion
                body, err := io.ReadAll(response.Body)
                if err != nil {
                    return fmt.Errorf("failed to read the response body: %w (status code %d)", err, response.StatusCode)
                }
                return fmt.Erorrf("unexpected status code received: %d (body: %s)", response.StatusCode, string(body))
```

2024-12-06 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +		time.Sleep(reportInterval)
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-12-06 16:28 UTC, s-shpak commented on internal/agent/service/service.go
> +	s.data["RandomValue"] = strconv.FormatFloat(rand.Float64(), 'g', -1, 64)
Это можно перенести выше, до взятия мьютекса

2024-12-06 16:28 UTC, s-shpak commented on internal/server/controller/index.go
> +		s.tpl = template.Must(template.ParseFiles("./web/template/index.html"))
1.

В Go функции и методы с префиксом Must паникую. Предполагается, что они должны использоваться тогда, когда потенциальную ошибку невозможно обработать (при объявлении глобальных переменных, в функции `init()` и т.п.). 

Не надо использовать функции `Must` в коде: используй те функции, которые они оборачивают и проверяй взвращаемые ими ошибки

2.

Достаточно распарсить темплейт один раз, при запуске программы. Вместо мьютекса ты можешь использовать функцию `sync.Once`

2024-12-06 16:28 UTC, s-shpak commented on internal/server/controller/index.go
> +				log.Printf("IndexHandlerFunc fmt.Fprintln: %v", err)
После этой строки лучше явно вызвать return, чтобы не забыть это сделать, если в будущем в конец этой фукнции будет добавлен какой-то код

2024-12-06 16:28 UTC, s-shpak commented on internal/server/controller/update.go
> +		if v, ok := m.GetStorageValue(name); ok {
Зачем это ?

2024-12-06 16:28 UTC, s-shpak commented on internal/server/repository/memstorage/memstorage.go
> +	if v, ok := s.data[t][name].(int64); ok {
Сейчас ты проверяешь не на наличие ключа, а на корректность каста значения к int64. Поправь это.

К тому же ты можешь переписать это так, чтобы обойтись без `else`, подумай как

2024-12-06 16:28 UTC, s-shpak commented on .golangci-1.62.yml
Не обязательно, можешь не использовать докер.

Этот комментарий можно зарезолвить

2024-12-06 16:28 UTC, s-shpak commented on internal/agent/agent.go
> +		time.Sleep(time.Second)
Да, пожалуйста. Сейчас стало лучше, ты сможешь написать сервис с какой-то сложной конкуретной логикой на первом и втором курсовом. Сейчас не надо, лучше сконцентрироваться на других моментах изучения го.

Этот комментарий можно зарезолвить

2024-12-06 18:54 UTC, korobkovandrey commented on internal/server/controller/index.go
> +		s.tpl = template.Must(template.ParseFiles("./web/template/index.html"))
изначально мьютекс сюда ввел, т.к. думал, что небезопасно в хандлере, работающему в горутинах обращаться к глобальным переменным внутри структуры шаблона, для начального парсинга следом получилось. Про sync.Once почитал, решил вынести парсинг на запуск - чтобы программа вылетала, если проблема с шаблоном.

2024-12-06 18:58 UTC, korobkovandrey commented on internal/server/controller/update.go
> +		if v, ok := m.GetStorageValue(name); ok {
Проверял, что все пишется, убрал.

2024-12-06 19:53 UTC, korobkovandrey commented on internal/agent/agent.go
> +		time.Sleep(reportInterval)
Использовал time.Tick, но связка select-case не потребовалась

2024-12-08 21:57 UTC, s-shpak requested changes

2024-12-08 21:57 UTC, s-shpak commented on internal/agent/agent.go
> +		for ; ; <-tick.C {
Более идиоматичным здесь будеть применить `for-range`: https://gobyexample.com/range-over-channels

2024-12-08 21:57 UTC, s-shpak commented on internal/server/server_test.go
> +	_ = os.Chdir("../..")
Я рекомендовал бы всегда проверять ошибки -- в том числе в тестах: даже если сейчас все работает корректно, то в будущем:
1. логика может поменяться
2. код может запускаться на другой платформе, где функционал `os` сработает по-другому

Даже если ошибка будет поймана дальше по коду теста (что не точно), будет сложнее понять, что именно пошло не так. Тем более ты используешь `require.NoError`, что до минимума уменьшает количество бойлерплейта

2024-12-08 21:57 UTC, s-shpak commented on internal/server/server_test.go
> +	require.NoError(t, err)
Кажется, что этот вызов должен быть на строку выше

2024-12-09 07:10 UTC, korobkovandrey commented on internal/agent/agent.go
> +		for ; ; <-tick.C {
Я хотел поведение - чтобы тикер сработал при запуске сразу. Через for-range - тогда при запуске в канал надо отправить tick.C <- time.Now(), но этот канал только на чтение. Тогда добавлять канал и значит городить через select-case, следовательно выносить выносить тело цикла в функцию. Либо оборачивать тикер в еще один и работать через другой канал, например так:
```go
	immediateTick := make(chan time.Time)
	go func(immediateTick chan time.Time) {
		immediateTick <- time.Now()
		for t := range time.Tick(time.Second) {
			immediateTick <- t
		}
	}(immediateTick)

	for range immediateTick {
		//...
	}
```

2024-12-09 13:25 UTC, s-shpak approved these changes

2024-12-09 14:44 UTC, merged